MovieApp/config/routes.rb
Rails.application.routes.draw do

  get '/movies' => 'movies#index'
  get '/movies/:id' => 'movies#show', as: :movie

  get '/actors' => 'actors#index'
  get '/actors/:id' => 'actors#show', as: :actor

end

MovieApp/app/models/actor.rb
class Actor < ActiveRecord::Base
	has_many :parts
	has_many :movies, through: :parts
end

MovieApp/app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :parts
	has_many :actors, through: :parts
end

MovieApp/app/models/part.rb
class Part < ActiveRecord::Base
	belongs_to :actor
	belongs_to :movie
end

MovieApp/app/controllers/actors_controller.rb
class ActorsController < ApplicationController

	def index
		@actors = Actor.all
	end

	def show
		@actor = Actor.find(params[:id])
		@movies = @actor.movies
	end
end

MovieApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

MovieApp/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	def index
		@movies = Movie.all
	end

	def show
		@movie = Movie.find(params[:id])
		@actors = @movie.actors
	end
end

MovieApp/app/helpers/actors_helper.rb
module ActorsHelper
end

MovieApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MovieApp/app/helpers/movies_helper.rb
module MoviesHelper
end

MovieApp/app/views/actors/index.html.erb
<div class="main">
	<%= @actors.each do |a| %>
		<div class="actor">
		<%= image_tag a.image %>
		<h3> <%= a.first_name %><%= a.last_name %> </h3>
		<p> <%= a.bio %></p>
		<%= link_to "Learn more", actor_path(a) %>
		</div>
	<% end %>
</div>

MovieApp/app/views/actors/show.html.erb
<div class="main actor-show">
  <div class="container">
    <div class="actor">
  
      <!-- Display the movie's info here -->
      <div class="info">
      <%= image_tag @actor.image %>
      <h3 class="actor-name"><%= @actor.first_name %><%= @actor.last_name %></h3>
      <p class="actor-bio"> <%= @actor.bio %> </p>
      </div>
      <h2>Cast</h2>
      <%= @movies.each do|m| %>
      <div class="info">
      <%= image_tag m.image %>
      <h3 class="movie-title"><%= m.title %></h3>
      <p class="movie-release_year"> <%= m.release_year %> </p>
      <p class="movie-plot"><%= m.plot %></p>
      <%= link_to "Learn more", movie_path(m) %>
      </div>
      <% end %>
     </div>
	</div>
</div>

MovieApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

MovieApp/app/views/movies/index.html.erb
<div class="main">
	<%= @movies.each do |m| %>
		<div class="movie">
		<%= image_tag m.image %>
		<h3> <%= m.title %> </h3>
		<p> <%= m.release_year %> </p>
		<p> <%= m.plot %> </p>
		<%= link_to "Learn more", movie_path(m) %>
		</div>
	<% end %>
</div>

MovieApp/app/views/movies/show.html.erb
<div class="main movie-show">
  <div class="container">
    <div class="movie">
  
      <!-- Display the movie's info here -->
      <div class="info">
      <%= image_tag @movie.image %>
      <h3 class="movie-title"><%= @movie.title %></h3>
      <p class="movie-release_year"> <%= @movie.release_year %> </p>
      <p class="movie-plot"><%= @movie.plot %></p>
      </div>
      <h2>Cast</h2>
      <%= @actors.each do|a| %>
      <div class="actor">
      <%= image_tag a.image %>
      <h3 class="actor-name"><%= a.first_name %><%= a.last_name %></h3>
      <p class="actor-bio"><%= a.bio %> </p>
      <%= link_to "Learn more", actor_path(a) %>
      </div>
      <% end %>
     </div>
	</div>
</div>